# Generated by Django 3.2.8 on 2021-12-04 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Is_Author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='Special_User',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 6, 39, 23, 40172, tzinfo=utc)),
        ),
    ]
