# Generated by Django 3.2.8 on 2021-12-04 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211204_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Is_Author',
            field=models.BooleanField(default=False, verbose_name='وضعیت نویسندگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Special_User',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 7, 7, 19, 469092, tzinfo=utc)),
        ),
    ]
