# Generated by Django 3.2.8 on 2021-12-24 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211204_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Special_User',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 6, 6, 3, 698877, tzinfo=utc)),
        ),
    ]
