# Generated by Django 3.2.8 on 2021-10-07 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Slug', models.SlugField(max_length=100, unique=True)),
                ('Thumbnail', models.ImageField(upload_to='images')),
                ('Published', models.DateTimeField(default=django.utils.timezone.now)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('p', 'published'), ('d', 'draft')], max_length=1)),
            ],
        ),
    ]
