# Generated by Django 3.2.8 on 2021-10-15 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('Slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس مخصوص دسته بندی')),
                ('Position', models.IntegerField(verbose_name='جایگاه')),
                ('Status', models.BooleanField(default=1, verbose_name='آیا منتشر شود؟')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['Position'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterField(
            model_name='article',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Description',
            field=models.TextField(verbose_name='شرح'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='آدرس مخصوص مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Status',
            field=models.CharField(choices=[('p', 'منتشر شده'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Thumbnail',
            field=models.ImageField(upload_to='images', verbose_name='تصویر مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Updated',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانی در'),
        ),
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ManyToManyField(to='blog.Categories', verbose_name='دسته بندی'),
        ),
    ]
