# Generated by Django 3.2.8 on 2021-10-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211015_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-Published'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['parent__id', 'Position'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AddField(
            model_name='categories',
            name='Parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='blog.categories', verbose_name='زیر دسته'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Category',
            field=models.ManyToManyField(related_name='articles', to='blog.Categories', verbose_name='دسته بندی'),
        ),
    ]
