# Generated by Django 3.2.8 on 2021-10-30 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_categories_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='blog.categories', verbose_name='زیر دسته'),
        ),
    ]
