# Generated by Django 3.2.8 on 2021-12-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_special',
            field=models.BooleanField(default=0, verbose_name='مقاله ویژه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Status',
            field=models.CharField(choices=[('p', 'منتشر شده'), ('d', 'پیش نویس'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت انتشار'),
        ),
    ]
